FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && apt-get install -y xz-utils

# COPY requirements.txt /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt --break-system-packages